### ISSUE TITLE
There's a new version in town

### ISSUE THREAD

**Issue by PatGitMaster** [jlesage/docker-crashplan-pro#292] opened 2021-03-17 12:54 UTC
I saw this on my log overnight:
Download of upgrade failed - version 1525200006860

**Comment by jvarrone** [comment] 2021-03-17 14:19
Ditto. Watchtower normally updates CP in the background. Is the new CP package just not ready yet? I keep getting "Upgrade Failed - Will try again..."

Thanks for all the work you put into the project!

**Comment by tomarikawa** [comment] 2021-03-17 16:05
I can confirm this (linux version running on Qnap NAS) latest tag v2.13.1, which runs crashplan-pro version 8.5.0.

8.6.0 is available since 15. March: https://support.code42.com/Release_Notes/Code42_app_version_8.6_release_notes

However, I can also confirm, that at current time being, 8.5.0 works properly: It can push the changes to CrashPlan's cloud. I wanted to mention this, because too old version CrashPlan server cannot push changes to Cloud anymore.

Absolutely fabulous work jlesage! You are a star.

**Comment by jlesage** [comment] 2021-03-17 16:07
Thanks for reporting, I will update the image with the new CP version.

**Comment by ThorEgilGit** [comment] 2021-03-19 07:55
Updated. Started OK - now synchronizing 12TB.

**Comment by jlesage** [comment] 2021-03-20 01:51
Perfect, we can now close this issue since CP 8.6.0 is now integrated in the latest Docker image.

**Closed by jlesage** 2021-03-20 01:51 UTC
