### ISSUE TITLE
 jlesage/crashplan-pro:latest not found....

### ISSUE THREAD

**Issue by dav1n** [jlesage/docker-crashplan-pro#413] opened 2023-02-06 21:59 UTC
Today, doing a simple docker pull is failing for me:

```
# docker pull jlesage/crashplan-pro
Using default tag: latest
Error response from daemon: manifest for jlesage/crashplan-pro:latest not found
```

**Comment by jlesage** [comment] 2023-02-07 00:50
Are you using a recent version of Docker ?

**Comment by dav1n** [comment] 2023-02-07 16:29
It's the same version on my QNAP that I've been using forever (and I will admit that I have not done a firmware update on the QNAP for quite a long time).  So it's likely fairly old, but it has worked for your crashplan-pro up until this latest release, and it still works for other docker pulls.

 # docker --version
Docker version 17.09.1-ce, build 0bbe3ac

**Comment by dav1n** [comment] 2023-02-07 17:42
I just tested in two ways:
 - tried to pull some of your other docker images - and all failed with the same error
 - tried to pull some other random docker images I found on dockerhub - and all succeeded.

So something weird is going on...

**Comment by jlesage** [comment] 2023-02-07 17:47
Image manifest has been updated with recent Docker image builder (see https://github.com/docker/buildx/releases) to be in OCI format.  I suspect the issue you are seeing is caused by that and your Docker version is too old to support the OCI format.

I can try to disable the provenance attestation to see if it helps.  But you should definitely try to upgrade your device, since more and more images will be build the new way.

**Comment by dav1n** [comment] 2023-02-07 18:18
Thanks.   That would be appreciated for now.

And yeah - I guess I do need to look into doing a firmware update on my QNAP.

**Comment by KamikazeFighter** [comment] 2023-02-08 04:35
I'm getting the same issue on unRAID 6.11.5 which I believe is the newest version.

**Comment by jlesage** [comment] 2023-02-08 11:55
For unRAID it's a different issue.  There is  a bug with the UI that prevents fetching the correct version.  You can install the "Docker Update Patch" plugin until the next version of unRAID is released.

**Comment by dav1n** [comment] 2023-02-08 12:37
Yes.  It successfully pulls now.  Thanks!!!

**Comment by jlesage** [comment] 2023-02-08 13:09
Great, thanks for confirming !

**Comment by KamikazeFighter** [comment] 2023-02-08 13:22
@jlesage Yeah, that fixed my problem as well.  Sorry, I thought they were connected.  I was only 1 version behind on this docker.

**Comment by jlesage** [comment] 2023-02-15 04:17
Closing this issue.

**Closed by jlesage** 2023-02-15 04:17 UTC
