### ISSUE TITLE
Upgraded to latest version and Crashplan started to backup everything again

### ISSUE THREAD

**Issue by BertXL** [jlesage/docker-crashplan-pro#293] opened 2021-03-21 13:48 UTC
I updated the docker image for jlesage/docker-crashplan-pro yesterday on my Synology NAS DS1513+ (as described here: https://github.com/jlesage/docker-crashplan-pro#synology ). After the update, Crashplan asked me to login, but not to adopt a backup. It started to synchronize the existing backup and now it is backing up **everything** all over again.

The way I understood, there were 2 options:
- CP recognizes the current backup on the device and it continues with the existing backup
- CP does not recognize the backup and it asks if you want to adopt a previous backup

Neither happened, and now I'm in a situation where my original files are available online but my current backup process will take 6 months to run since the total set of files that have to be backed up are +/- 2.5TB. 
 
Any suggestions? (fyi I'm not a technician and the Synology docker host is not very flexible)

**Comment by met152** [comment] 2021-03-21 14:27
I'm having the exact same issue. Synology DS920+ running crashplan pro in Docker.

**Comment by tomarikawa** [comment] 2021-03-21 21:41
Sorry to hear.

I can confirm, that on Qnap NAS (TS-451+ with the latest FW QTS 4.5.2.1556-build2021020), the latest crashplan Pro v8.6.0 (Tag v2.14.0), recognized my existing cloud backup and external HD backups and has now synced all the changes.

**Comment by jlesage** [comment] 2021-03-22 00:59
So your backup set didn't change ?  Nor the paths inside the container ?
You can have a look at the history to see if it really re-upload everything.  I don't know what happened, but if files are already online, CrashPlan will probably have nothing to upload because of the deduplication process.

**Comment by met152** [comment] 2021-03-23 10:24
> So your backup set didn't change ? Nor the paths inside the container ?
> You can have a look at the history to see if it really re-upload everything. I don't know what happened, but if files are already online, CrashPlan will probably have nothing to upload because of the deduplication process.

Nothing changed. However your response to the other issue opened on this topic (#295) answered my question.  Apparently I never mapped the config path...
I just finished my initial backup of 2TB+ that took 30+ days.  Oh well, better to learn now.

**Comment by jlesage** [comment] 2021-03-23 11:06
If you choose to adopt a backup (replace a device), CrashPlan won't have to re-upload everything.

**Comment by BertXL** [comment] 2021-03-23 16:33
I don't understand it anymore... I have 4 separate backup sets, the first one misbehaved and backed up completely again, which took 3d for 300GB. The 3 other ones now seem to run as they should, and have 'backed up' 2.5TB on less than a day.
The backup set which did not work as expected , is the one which actively syncs which my laptop. I suspect it must be something with date attributes... 
Thank you all for your help and suggestions

**Comment by met152** [comment] 2021-03-24 10:21
> If you choose to adopt a backup (replace a device), CrashPlan won't have to re-upload everything.

Thanks! This seems to have worked.  Likely user error, but the first couple times I tried it wanted to restore files to my Synology, seemingly by downloading everything from the cloud to my NAS.  It is now in the process of "synchronizing block information" and is about halfway done.  Thanks again!

**Comment by jlesage** [comment] 2023-11-11 14:50
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2023-11-11 14:50 UTC
