### ISSUE TITLE
v2.6.3+ boot error

### ISSUE THREAD

**Issue by gokuu** [jlesage/docker-crashplan-pro#173] opened 2019-04-26 20:42 UTC
First of all, thanks for the awesome container :)

Now for the bad part, after upgrading to v2.6.3, my container went into a boot loop, with the following error on the `service.log.0` file:
```
[04.26.19 18:04:40.701 INFO  main           com.backup42.service.CPService] *************************************************************
[04.26.19 18:04:40.701 INFO  main           com.backup42.service.CPService] STARTED CrashPlanService
[04.26.19 18:04:40.702 INFO  main           com.backup42.service.CPService] CPVERSION = 6.9.4 - 1525200006694 (2018-05-01T18:40:06:694+0000) - Build: 502
[04.26.19 18:04:40.707 INFO  main           com.backup42.service.CPService] LOCALE = English (United States)
[04.26.19 18:04:40.707 INFO  main           com.backup42.service.CPService] ARGS = []
[04.26.19 18:04:40.707 INFO  main           com.backup42.service.CPService] *************************************************************
[04.26.19 18:04:41.033 INFO  main           com.backup42.service.CPService] Adding shutdown hook.
[04.26.19 18:04:41.090 INFO  main           com.backup42.service.CPService] loadConfig, BEGIN Loading Configuration
[04.26.19 18:04:41.119 INFO  main         backup42.common.config.AppConfig]   Loading from default: , conf/default.service.xml
[04.26.19 18:04:41.204 INFO  main         backup42.common.config.AppConfig]   Loading from my xml file:, /usr/local/crashplan/conf/my.service.xml
[04.26.19 18:04:41.261 INFO  main         e42.jna.openssl.OpenSSLCryptoLib] OPENSSL::Initializing OpenSSL
[04.26.19 18:04:41.261 INFO  main         e42.jna.openssl.OpenSSLCryptoLib] OPENSSL::Loading OpenSSLCryptoLib Library: 'netty_tcnative'
[04.26.19 18:04:41.276 WARN  main         backup42.common.config.AppConfig] Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL, com.code42.exception.DebugException: Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL
STACKTRACE:: com.code42.exception.DebugException: Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL
	at com.backup42.common.config.AppConfig.load(AppConfig.java:139)
	at com.backup42.common.config.ServiceConfig.load(ServiceConfig.java:421)
	at com.backup42.service.CPService.loadConfig(CPService.java:1183)
	at com.backup42.service.CPService.start(CPService.java:506)
	at com.backup42.service.CPService.main(CPService.java:1986)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL
	at com.code42.hash.MD5Digest.<init>(MD5Digest.java:24)
	at com.code42.utils.OsPatternList.getChecksum(OsPatternList.java:141)
	at com.code42.utils.PatternList.equals(PatternList.java:389)
	at com.code42.utils.OsPatternList.equals(OsPatternList.java:276)
	at java.util.Objects.equals(Objects.java:59)
	at com.code42.config.ConfigXmlTransformer.fromXmlConfigItem(ConfigXmlTransformer.java:558)
	at com.code42.config.ConfigXmlTransformer.fromXmlAConfigItem(ConfigXmlTransformer.java:432)
	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:332)
	at com.code42.config.ConfigXmlTransformer.fromXmlConfigComponent(ConfigXmlTransformer.java:600)
	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:334)
	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:87)
	at com.code42.xml.XmlTool.fromXml(XmlTool.java:201)
	at com.code42.xml.XmlTool.fromXml(XmlTool.java:182)
	at com.code42.config.AConfig.fromXml(AConfig.java:77)
	at com.code42.config.AConfigFile.fromXml(AConfigFile.java:65)
	at com.backup42.common.config.AppConfig.load(AppConfig.java:136)
	... 4 more

[04.26.19 18:04:41.277 ERROR main                                         ] com.code42.exception.DebugException: Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL
[04.26.19 18:04:41.277 ERROR main                                         ] 	at com.backup42.common.config.AppConfig.load(AppConfig.java:139)
[04.26.19 18:04:41.277 ERROR main                                         ] 	at com.backup42.common.config.ServiceConfig.load(ServiceConfig.java:421)
[04.26.19 18:04:41.277 ERROR main                                         ] 	at com.backup42.service.CPService.loadConfig(CPService.java:1183)
[04.26.19 18:04:41.278 ERROR main                                         ] 	at com.backup42.service.CPService.start(CPService.java:506)
[04.26.19 18:04:41.278 ERROR main                                         ] 	at com.backup42.service.CPService.main(CPService.java:1986)
[04.26.19 18:04:41.278 ERROR main                                         ] Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL
[04.26.19 18:04:41.278 ERROR main                                         ] 	at com.code42.hash.MD5Digest.<init>(MD5Digest.java:24)
[04.26.19 18:04:41.278 ERROR main                                         ] 	at com.code42.utils.OsPatternList.getChecksum(OsPatternList.java:141)
[04.26.19 18:04:41.278 ERROR main                                         ] 	at com.code42.utils.PatternList.equals(PatternList.java:389)
[04.26.19 18:04:41.279 ERROR main                                         ] 	at com.code42.utils.OsPatternList.equals(OsPatternList.java:276)
[04.26.19 18:04:41.279 ERROR main                                         ] 	at java.util.Objects.equals(Objects.java:59)
[04.26.19 18:04:41.279 ERROR main                                         ] 	at com.code42.config.ConfigXmlTransformer.fromXmlConfigItem(ConfigXmlTransformer.java:558)
[04.26.19 18:04:41.279 ERROR main                                         ] 	at com.code42.config.ConfigXmlTransformer.fromXmlAConfigItem(ConfigXmlTransformer.java:432)
[04.26.19 18:04:41.279 ERROR main                                         ] 	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:332)
[04.26.19 18:04:41.279 ERROR main                                         ] 	at com.code42.config.ConfigXmlTransformer.fromXmlConfigComponent(ConfigXmlTransformer.java:600)
[04.26.19 18:04:41.280 ERROR main                                         ] 	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:334)
[04.26.19 18:04:41.280 ERROR main                                         ] 	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:87)
[04.26.19 18:04:41.280 ERROR main                                         ] 	at com.code42.xml.XmlTool.fromXml(XmlTool.java:201)
[04.26.19 18:04:41.280 ERROR main                                         ] 	at com.code42.xml.XmlTool.fromXml(XmlTool.java:182)
[04.26.19 18:04:41.280 ERROR main                                         ] 	at com.code42.config.AConfig.fromXml(AConfig.java:77)
[04.26.19 18:04:41.280 ERROR main                                         ] 	at com.code42.config.AConfigFile.fromXml(AConfigFile.java:65)
[04.26.19 18:04:41.280 ERROR main                                         ] 	at com.backup42.common.config.AppConfig.load(AppConfig.java:136)
[04.26.19 18:04:41.281 ERROR main                                         ] 	... 4 more
[04.26.19 18:04:41.285 INFO  main                                         ] XML FILE CONTENTS: /usr/local/crashplan/conf/my.service.xml -----------
```
Followed by the XML contents.
If I downgrade to v2.6.3, the same error occurs, but if I downgrade to v2.6.2, everything works. 

Any idea why?

Thanks

**Comment by jlesage** [comment] 2019-04-27 18:00
I don't have this issue.  Are you using your own encryption key?

**Comment by gokuu** [comment] 2019-04-28 09:44
Yes, I am. But I've been using the same custom encryption key for quite a while now (at least more than a year)

**Comment by jlesage** [comment] 2019-04-30 18:47
The issue seems related to the CP version 6.9.4.

Can you verify with CP support team if this is a known issue?  I will try to reproduce on my side...

**Comment by jlesage** [comment] 2019-05-07 00:45
So I tried to reproduce by configuring a device with a custom encryption key, without success.

Where you able to contact the CrashPlan support?

**Comment by gokuu** [comment] 2019-05-07 12:50
Sorry for not responding earlier, it's been a bit hectic :)

I've got in contact with them, but once I told them it was running on a
docker container, they immediately 'set me aside', as it is not one of
their supported platforms. :(

**Comment by jlesage** [comment] 2019-05-10 02:18
Yeah this is very unfortunate...
I forgot to precise that we should not mention "docker container" when contacting the support.

**Comment by jlesage** [comment] 2019-05-10 02:20
If you are interested in helping debugging this issue, you could provide remote access to your container or a copy of the container's appdata.  Since I cannot reproduce on my side, there are a couple of things I can investigate using your setup.

**Comment by gokuu** [comment] 2019-05-10 20:58
Hi, since part of what I'm backing up is actually sensitive data, I'd
prefer not to grant remote access to the container. Where can I find the
appdata for the container? If I see that there's no sensitive data there, I
have no problem with sharing that :)

**Comment by jlesage** [comment] 2023-11-11 14:56
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2023-11-11 14:56 UTC
