### ISSUE TITLE
Install older version?

### ISSUE THREAD

**Issue by GradientEcho** [jlesage/docker-crashplan-pro#74] opened 2018-04-06 01:35 UTC
Docker was running previously but stopped after a QNAP update and possibly a newer version of crashplan.  How do I install an older version?

Presently, starting the docker just gives this:

`[CrashPlanEngine] starting...                                                                                                               
[CrashPlanEngine] starting...                                                                                                               
[CrashPlanEngine] starting...                                                                                                               
[CrashPlanEngine] starting...                                                                                                               
[CrashPlanEngine] starting...`

**Comment by jlesage** [comment] 2018-04-06 01:48
You can install a specific version by using the docker image tag.  But I guess we need to know the version you are running currently.  Also, providing this information would help determine the issue:
  - Output of `docker inspect <container name>`.
  - The `log/service.log.0` file (on the host, in the directory you mapped to `/config`).

**Comment by berwalkb** [comment] 2018-04-06 03:35
I'm was seeing the same v2.3.2 "starting...starting..." issue which I have now resolved; simply put, I'm nearly certain that changing the container user/group ID parameters to root values is what fixed the issue.

I'm running on Synology with Docker package v17.05.0-0370.  The symptom is observable under the web UI as a red X in the top left corner, or a "cannot connect to service" error in center of page.  The container log revealed the "starting...starting..." error.

It had been working immediately prior on docker-crashplan-pro v2.3.1, configured from root CLI to run container under non-root account.  It had been working for a month just fine, but since CrashPlan was complaining that it wanted to update to new version, I set out to upgrade to docker-crashplan-pro v2.3.2.  I deleted v2.3.1 image and container.

I used the exact same method as I had used previously (as root, using same container configuration settings, to run under non-root account), but the newly created container based on docker-crashplan-pro v2.3.2 soon exhibited the symptoms at top.  I double-checked the container configuration parameters between OS and container were all still good.  I was then hoping it was a Crashplan application upgrade issue and not a docker image issue, so I then deleted the contents of the /config directory (in hindsight, this was probably unnecessary) and tried creating container fresh again the same way, but the symptoms persisted.

Finally, I created a new container with user ID and group ID container parameters set to run under root, and that seems to have resolved the problem.  I'll mention that I had again deleted the contents of the /config directory for a fresh install, but this was probably unnecessary (I'm mentioning it just incase it turns out to be pertinent).  

I only have one environment, and it's currently working, so I'm not messing with it further.  Thus, I can't verify exactly which of the actions actually resolved the problem.  I'm nearly certain it was changing the user/group ID to root that actually resolved it.  

Let me know if you have any questions.  I hope this helps.

jlesage - Thanks for all your hard work on this image and support!

**Comment by jlesage** [comment] 2018-04-06 09:34
It would be nice if you could reproduce the issue using a second instance of the container.
Usually, starting the container with the wrong `USER_ID`/`GROUP_ID` doesn't prevent CrashPlan to correctly starts.  It just prevents it to read and backup your data.
Running as root should not be required to run CrashPlan.  It's for this reason that more investigation on your problem would be interesting to be sure that there is no another/different issue.

**Comment by jlesage** [comment] 2018-04-06 23:52
Could you provide the following information for this instance:
  - Output of `docker inspect <name of the container>`.
  - The `log/service.log.0` file.
Thanks!

**Comment by berwalkb** [comment] 2018-04-07 03:16
Requested files attached.  Please delete post once received (if possible).  Thanks.

[berwalkb_docker-crashplan-pro_troubleshoot_v2.3.2.zip](https://github.com/jlesage/docker-crashplan-pro/files/1886001/berwalkb_docker-crashplan-pro_troubleshoot_v2.3.2.zip)

**Comment by jlesage** [comment] 2018-04-08 01:09
For the non-root case, the `service.log.0` file is empty.  Is it correct?  If yes, then could you also provide the following files:
  - `log/engine_error.log`
  - `log/engine_output.log`

For the post, you should be able to edit your own messages (I cannot do it).

**Comment by jlesage** [comment] 2023-11-11 14:52
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2023-11-11 14:52 UTC
