### ISSUE TITLE
Stating more space to back up then is available in the entire server. 

### ISSUE THREAD

**Issue by paradoxgrowth** [jlesage/docker-crashplan-pro#279] opened 2021-01-19 00:43 UTC
Thanks to jlesage for making this container! I have about 3 TB worth of data selected to back up. However, once it scans, it reports I have selected 148 TB. This is not possible because I only have about 10 TB in the entire sever. I have deleted and rebuilt from scratch 3 times with the same result. I don't get it, does anyone know why this is happening and should I be worried?

More info, I am running the container within container station in my ts-677 qnap NAS. All software is the latest version.

If there is a way to access the crashplan console maybe I could tell it to sync?

Thanks for your help!

**Comment by jlesage** [comment] 2021-01-19 00:58
This is usually caused by having the Docker related directory part of the backup.  I'm not sure what is the exact one on QNAS, but the typical path is `/var/lib/docker`.  It should not be part of the backup.

**Comment by paradoxgrowth** [comment] 2021-01-19 12:26
Yup that did it, thanks so much!!! For me there could be two places to avoid. One in /CACHDEV/Virtualize and /CACHDEV/.qpkg/where ever contain station lives (haven’t figured it out yet).

**Comment by jlesage** [comment] 2023-11-11 14:41
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2023-11-11 14:41 UTC
