### ISSUE TITLE
Password limited to 8 chars

### ISSUE THREAD

**Issue by milindbl** [jlesage/docker-crashplan-pro#24] opened 2017-12-19 19:44 UTC
Hi, just noticed that when setting password, either by using "Environment variables" VNC_PASSWORD or by creating .vncpass_clear in /config: Only the first 8 chars of the password seem to be relevant.

Even if I have an 20 char password, just entering the first 8 chars will give me access.

**Comment by jlesage** [comment] 2017-12-19 19:51
This is a limit of the VNC/RFB protocol.  See https://tools.ietf.org/html/rfc6143, section 7.2.2.

So this is not a bug, but thanks for raising the question, I will update the documentation with this !

**Comment by milindbl** [comment] 2017-12-19 20:03
Ahh.. ok, wish it would be longer, but then I know. Tnx for super fast support!

**Comment by jlesage** [comment] 2017-12-19 20:17
Let's keep the issue open, just to make sure I don't forget to change the README ;)

**Comment by jlesage** [comment] 2017-12-20 19:33
README updated.  Closing the issue.

**Closed by jlesage** 2017-12-20 19:33 UTC
